version: "2.4"
services:
  nginxproxy:
      image: nginx:mainline-alpine
      command: "/bin/sh -c 'while :; do sleep 48h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
      environment:
        - TZ=${TZ}
      volumes:
        - ./data/nginx/conf:/etc/nginx/conf.d/:ro
        - ./data/letsencrypt/webroot:/usr/share/nginx/html:ro
        - ./data/letsencrypt/conf:/etc/letsencrypt:ro
        #- /opt/mailcow-dockerized/data/assets/ssl:/etc/ssl/mail/:ro
      ports:
        - "${HTTPS_BIND:-0.0.0.0}:${HTTPS_PORT:-443}:${HTTPS_PORT:-443}"
        - "${HTTP_BIND:-0.0.0.0}:${HTTP_PORT:-80}:${HTTP_PORT:-80}"
      restart: always
      network_mode: "host"

  certbot:
    image: certbot/certbot
    restart: always
    depends_on:
      - nginxproxy
    environment:
        - TZ=${TZ}
    volumes:
      - ./data/letsencrypt/conf:/etc/letsencrypt
      - ./data/letsencrypt/lib:/var/lib/letsencrypt
      - ./data/letsencrypt/webroot:/data/letsencrypt
      - ./data/letsencrypt/logs:/var/log/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 24h & wait $${!}; done;'"
    networks:
      frontend-nw:

networks:
  frontend-nw:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-nginxproxy
